Repository chronoscio/frontend, pull requests merged in 2018-10, with the labels that each got.

#27 Wire up to backend
  packages/app/components/LeftPane/LeftPane.tsx
  packages/app/components/LeftPane/Pages/Pages.tsx
  packages/app/components/MainMap/decorators/onlyCurrentGeojson.ts
  packages/app/components/MainMap/decorators/territoriesToGeojson.ts
  packages/app/components/MainMap/decorators/withFetchTerritories.ts
  packages/app/components/MainMap/decorators/withHandleTerritoryClick.ts
  packages/app/components/Nation/Nation.tsx
  packages/app/components/Nation/Territories/Territories.tsx
  packages/app/components/mockData.ts
  packages/app/now-secrets.example.json
  packages/app/package.json
  packages/app/pages/map.tsx
  yarn.lock
Labels: status/waits for review

#24 Create @chronoscio/api interface with backend
  packages/api/README.md
  packages/api/package.json
  packages/api/src/api/diplomaticRelations.ts
  packages/api/src/api/index.ts
  packages/api/src/api/politicalEntities.ts
  packages/api/src/api/territories.ts
  packages/api/src/index.ts
  packages/api/src/models/DiplomaticRelation.ts
  packages/api/src/models/Entity.ts
  packages/api/src/models/PoliticalEntity.ts
  packages/api/src/models/Territory.ts
  packages/api/src/models/index.ts
  packages/api/src/models/utils/index.ts
  packages/api/src/models/utils/validateForRFF.ts
  packages/api/tsconfig.json
  packages/app/components/CurrentDate/decorators/withCurrentDate.ts
  packages/app/components/EditTerritory/CloseButton/decorators/withHandleClose.ts
  packages/app/components/EditTerritory/EditTerritory.tsx
  packages/app/components/EditTerritory/decorators/loadCurrentTerritory.ts
  packages/app/components/EditTerritory/decorators/withEditTerritoryStore.ts
  packages/app/components/Errors/Errors.tsx
  packages/app/components/Errors/decorators/withErrorStore.ts
  packages/app/components/Errors/index.ts
  packages/app/components/LeftPane/LeftPane.tsx
  packages/app/components/LeftPane/Pages/Pages.tsx
  packages/app/components/LeftPane/Welcome/WelcomeList/WelcomeList.tsx
  packages/app/components/Login/Callback/Callback.tsx
  packages/app/components/Login/decorators/withLogin.ts
  packages/app/components/MainMap/MainMap.tsx
  packages/app/components/MainMap/decorators/onlyCurrentGeojson.ts
  packages/app/components/MainMap/decorators/territoriesToFC.ts
  packages/app/components/MainMap/decorators/territoriesToGeojson.ts
  packages/app/components/MainMap/decorators/withFetchTerritories.ts
  packages/app/components/MainMap/decorators/withHandleTerritoryClick.ts
  packages/app/components/MainMap/decorators/withSelectedTerritory.ts
  packages/app/components/MainMap/decorators/withTerritories.ts
  packages/app/components/Nation/Nation.tsx
  packages/app/components/Nation/NewNation/NewNation.tsx
  packages/app/components/Nation/NewNation/decorators/withHandleSubmit.ts
  packages/app/components/Nation/Territories/Territories.tsx
  packages/app/components/Nation/decorators/withCurrentNation.ts
  packages/app/components/Nation/decorators/withGoToWelcome.ts
  packages/app/components/mockData.ts
  packages/app/now-secrets.example.json
  packages/app/now.json
  packages/app/package.json
  packages/app/pages/map.tsx
  packages/app/routes.js
  tslint.json
  yarn.lock
Labels: status/waits for review

#29 Update packages
  packages/app/package.json
  packages/app/pages/_document.tsx
  packages/app/pages/callback.tsx
  packages/app/pages/empty.css
  packages/ui/package.json
  tslint.json
  yarn.lock
Labels: status/waits for review

#32 Clarify Installation and Documentation
  README.md
Labels: status/reviewed

#34 Redirect if no territory found
  packages/app/pages/map.tsx
Labels: status/waits for review

#35 Update API for new response
  packages/api/src/api/politicalEntities.ts
  packages/api/src/models/Territory.ts
  packages/app/components/MainMap/decorators/territoriesToFC.ts
  packages/app/components/MainMap/decorators/withHandleTerritoryClick.ts
  packages/app/components/Nation/Territories/Territories.tsx
Labels: kind/bug, status/reviewed

#37 Fix Edit button not clickable
  packages/api/src/models/PoliticalEntity.ts
  packages/app/components/Nation/Territories/Territories.tsx
Labels: status/waits for review

#42 Create one common interface for raw api calls
  packages/api/src/api/diplomaticRelations.ts
  packages/api/src/api/index.ts
  packages/api/src/api/politicalEntities.ts
  packages/api/src/api/territories.ts
  packages/api/src/api/utils/apiEndpoint.ts
  packages/api/src/api/utils/returnResponse.ts
  packages/api/src/models/DiplomaticRelation.ts
Labels: status/waits for review

#38 Decode geobuf
  packages/api/package.json
  packages/api/src/ambient.d.ts
  packages/api/src/models/Territory.ts
  yarn.lock
Labels: kind/feature, status/reviewed
