Repository chronoscio/frontend, pull requests merged in 2018-08, with the labels that each got.

#6 Add authentication
  README.md
  package.json
  packages/app/.babelrc.js
  packages/app/components/Login/Callback/Callback.ts
  packages/app/components/Login/Callback/decorators/handleAuthentication.ts
  packages/app/components/Login/Callback/index.ts
  packages/app/components/Login/LoggedInMenu/Avatar/Avatar.tsx
  packages/app/components/Login/LoggedInMenu/Avatar/index.ts
  packages/app/components/Login/LoggedInMenu/LoggedInMenu.tsx
  packages/app/components/Login/LoggedInMenu/index.ts
  packages/app/components/Login/Login.tsx
  packages/app/components/Login/decorators/withAuth.ts
  packages/app/components/Login/decorators/withLogin.ts
  packages/app/components/Login/index.ts
  packages/app/components/MainMap/Draw/Draw.tsx
  packages/app/components/MainMap/Draw/decorators/withDrawUpdate.ts
  packages/app/components/MainMap/Draw/index.ts
  packages/app/components/MainMap/MainMap.tsx
  packages/app/components/MainMap/index.tsx
  packages/app/index.d.ts
  packages/app/next.config.js
  packages/app/now-secrets.example.json
  packages/app/now.json
  packages/app/package.json
  packages/app/pages/_document.js
  packages/app/pages/callback.tsx
  packages/app/pages/index.tsx
  yarn.lock
Labels: status/waits for review

#7 Meta information about the project
  .travis.yml
  README.md
  docs/DEVELOPER.md
  packages/app/now.json
Labels: status/await, status/waits for review

#9 Fix travis badge
  README.md
Labels: status/reviewed

#10 Add basic UI components
  packages/app/ambient.d.ts
  packages/app/components/LeftPane/LeftPane.tsx
  packages/app/components/LeftPane/index.ts
  packages/app/components/Login/Callback/Callback.tsx
  packages/app/components/Login/Callback/decorators/handleAuthentication.ts
  packages/app/components/Login/LoggedInMenu/Avatar/Avatar.tsx
  packages/app/components/Login/Login.tsx
  packages/app/components/Login/decorators/withLogin.ts
  packages/app/components/MainMap/Draw/Draw.tsx
  packages/app/components/MainMap/Draw/decorators/addGeojson.ts
  packages/app/components/MainMap/Draw/decorators/withDrawUpdate.ts
  packages/app/components/MainMap/Edit/Edit.tsx
  packages/app/components/MainMap/Edit/index.ts
  packages/app/components/MainMap/MainMap.css
  packages/app/components/MainMap/MainMap.tsx
  packages/app/components/MainMap/decorators/closeEditMode.ts
  packages/app/components/MainMap/decorators/onlyCurrentTerritories.ts
  packages/app/components/MainMap/decorators/territoriesToGeojson.ts
  packages/app/components/MainMap/decorators/withFetchTerritories.ts
  packages/app/components/MainMap/index.ts
  packages/app/components/Nation/CurrentDate/CurrentDate.tsx
  packages/app/components/Nation/CurrentDate/index.ts
  packages/app/components/Nation/Nation.tsx
  packages/app/components/Nation/Territories/Territories.tsx
  packages/app/components/Nation/Territories/index.ts
  packages/app/components/Nation/index.ts
  packages/app/components/decorators/withCurrentDate.ts
  packages/app/components/decorators/withEditMode.ts
  packages/app/components/mockData.ts
  packages/app/package.json
  packages/app/pages/_document.tsx
  packages/app/pages/index.tsx
  packages/app/pages/map.tsx
  packages/app/routes.d.ts
  packages/app/routes.js
  packages/app/server.js
  packages/app/types.d.ts
  yarn.lock
Labels: status/waits for review
